site_name: Enhanced Developer Experience with AI and GitLab
site_description: A comprehensive guide to integrating AI with GitLab for enhanced developer experience
site_author: Sebastien BRUN

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - with-pdf:
      author: Sebastien BRUN
      copyright: "2024"
      enabled_if_env: ENABLE_PDF_EXPORT
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Design:
      - Architecture: design/architecture.md
      - Component Model: design/component-model.md
      - Context & Personas: design/context-and-personas.md
      - GitLab MCP Server: design/gitlab-mcp-server.md
  - Use Cases:
      - All Use Cases: use-cases/use-cases.md
  - Implementation:
      - Prerequisites: prerequisites.md
      - Setup: implementation/setup.md
      - Docker Compose: implementation/docker-compose.md
      - MCP Integration: implementation/mcp-integration.md
      - IDE Configuration: implementation/ide-config.md
      - Contributing: implementation/contributing.md
